apiVersion: apps/v1
kind: Deployment
metadata:
  name: md-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: md-springboot
  template:
    metadata:
      labels:
        app: md-springboot
    spec:
      containers:
        - name: springboot
          image: mdmunna67/md-docker-demo:md-docker-demo
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: md-springboot
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: md-springboot